# Generated by Django 4.0.3 on 2022-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='award',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
